HW8-game-eagley-kasner/HW8-game-eagley-kasner/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW8_game_eagley_kasner.Controllers
{
    public class GameController : Controller
    {
        private ModelHighscoreContainer db = new ModelHighscoreContainer();

        // GET: Game
        public ActionResult Index(string playerName)
        {
            HighScore currentPlayer = new HighScore();
            currentPlayer.PlayerName = playerName;
            if (playerName != null)
            {
                return View(currentPlayer);
            }
            else
            {
                return RedirectToRoute("Home");
            }

        }

        public ActionResult GameOver(string playerName, int score, int wavesCompleted)
        {
            HighScore ply = new HighScore();
            ply.PlayerName = playerName;
            ply.Points = score;
            ply.WavesCompleted = wavesCompleted.ToString();//made a string due do db mistake, could fix, but not going to

            db.HighScores.Add(ply);
            db.SaveChanges();

            return View(ply);
        }
    }
}

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Controllers/HighScoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW8_game_eagley_kasner;

namespace HW8_game_eagley_kasner.Controllers
{
    public class HighScoresController : Controller
    {
        private ModelHighscoreContainer db = new ModelHighscoreContainer();

        // GET: HighScores
        public ActionResult Index()
        {
            return View(db.HighScores.ToList());
        }

        // GET: HighScores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HighScore highScore = db.HighScores.Find(id);
            if (highScore == null)
            {
                return HttpNotFound();
            }
            return View(highScore);
        }

        // GET: HighScores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HighScores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Points,WavesCompleted,PlayerName")] HighScore highScore)
        {
            if (ModelState.IsValid)
            {
                db.HighScores.Add(highScore);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(highScore);
        }

        // GET: HighScores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HighScore highScore = db.HighScores.Find(id);
            if (highScore == null)
            {
                return HttpNotFound();
            }
            return View(highScore);
        }

        // POST: HighScores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Points,WavesCompleted,PlayerName")] HighScore highScore)
        {
            if (ModelState.IsValid)
            {
                db.Entry(highScore).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(highScore);
        }

        // GET: HighScores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HighScore highScore = db.HighScores.Find(id);
            if (highScore == null)
            {
                return HttpNotFound();
            }
            return View(highScore);
        }

        // POST: HighScores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HighScore highScore = db.HighScores.Find(id);
            db.HighScores.Remove(highScore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HW8_game_eagley_kasner.Controllers
{
    public class HomeController : Controller
    {
        private ModelHighscoreContainer db = new ModelHighscoreContainer();

        // GET: HighScores
        public ActionResult Index()
        {
            return View(db.HighScores.OrderByDescending(w=>w.Points).ToList());
        }
    }
}

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/Game/GameOver.cshtml
@model HW8_game_eagley_kasner.HighScore

@{
    ViewBag.Title = "GameOver";
}

<h2>GameOver</h2>

<div>
    <h4>HighScore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WavesCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WavesCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>

    </dl>
</div>
@using (Html.BeginForm("Index", "Game"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Your game-name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("PlayerName", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("PlayerName", new { @class = "text-danger", @value= Model.PlayerName })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Play again!" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@*<p>
    @Html.ActionLink("Play again!", "Index", "Game", new { area = "" }, Model.PlayerName)
</p>*@

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/Game/Index.cshtml
@model HighScore
@{
    ViewBag.Title = Model.PlayerName;
}
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />

<h2>Breakout - <span id="gameScore">0</span></h2>
<canvas id="gameField" width="400" height="480" style="background-color:midnightblue"></canvas>
<p>
    Controls: A - left, D - right
</p>
<script src="~/Scripts/Game/KeyboardControls.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Paddle.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Ball.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Walls.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Physics.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Brick.js" type="text/javascript"></script>
<script src="~/Scripts/Game/Score.js" type="text/javascript"></script>
<script src="~/Scripts/Game/DOOM.js" type="text/javascript"></script>
<script>
    //game goes here
    //dom references
    var myCanvas = document.getElementById("gameField");
    var ctx = myCanvas.getContext("2d");
    var playerPaddle;

    var somethingDied = false;
    var scanningForDead = false;

    //engine bay
    physics = makePhysics();
    //animation engine
    var Animator = {
        renderItems: [],
        animTimeout: null,
        isRunningGame: true,
        renderTick:0,
        renderVisibleObjects: function () {
            for (item in Animator.renderItems) {
                if (Animator.renderItems[item].draw !== undefined) {
                    ctx.save();
                    Animator.renderItems[item].draw(ctx);
                    ctx.restore();
                }
            }
        },
        clearCanvas: function() {
            ctx.clearRect(0, 0, myCanvas.width,myCanvas.height);
            var w =myCanvas.width;
            myCanvas.width = 1;
            myCanvas.width = w;
        },
        animationLoop: function () {
            physics.calculateDelta();
            physics.movePhysicsObjects();
            if (Animator.renderTick >= 2) {
                //only render every 3 frames
                Animator.renderTick = 0;
                Animator.clearCanvas();
                Animator.renderVisibleObjects();
            } else {
                //if not a rendertick, do other laggy things
                Animator.renderTick++;
                checkForGameOver("@Model.PlayerName");
                if (somethingDied) {
                    removeDeadItems();
                }
            }
            if (Animator.isRunningGame) {
                animTimeout = setTimeout(Animator.animationLoop, 20);
            }
        }
    }
    //map engine
    var cartographer = {
        bricks: [],
        balls: [],
        walls: [],
        deadBricks:0,
        killBrick: function () {
            cartographer.deadBricks++;
            if (cartographer.bricks.length <= cartographer.deadBricks) {
                cartographer.deadBricks = 0;
                for (var br in cartographer.bricks) {
                    cartographer.bricks.pop();
                }
                cartographer.bricks = [];
                resetMap();
            }
        }
    }

    //physics templates
    function Transform() {
        var transform = {
            x: 0,
            y: 0,
            width: 10,
            height: 10,
            center: function () {

                return {
                    x: transform.x + (transform.width / 2),
                    y: transform.y + (transform.height / 2)
                };
            },
            velocity: {
                angle: 0,
                speed: 0,
                nextPosition: function () {
                    return {
                        x: transform.x + (transform.velocity.speed * Math.cos(transform.velocity.angle) * physics.deltaTime / 1000),
                        y: transform.y + (transform.velocity.speed * Math.sin(transform.velocity.angle) * physics.deltaTime / 1000)
                    };
                },
                move: function () {
                    var next = transform.velocity.nextPosition();
                    if (next.x !== 0 || next.y !== 0) {
                        transform.x = next.x;
                        transform.y = next.y;
                    }
                }
            },
            refresh: function () {
                transform.velocity.move();
            }
        }
        return transform;
    }

    function addNewPhysicsItemToField(item) {
        Animator.renderItems.push(item);
        physics.collisionItems.push(item);
    }

    console.log(makePlayerPaddle);

    //a few map builders:
    function defaultBallAndPlayer() {
        playerPaddle = makePlayerPaddle(myCanvas.width / 2, myCanvas.height * 0.15);
        //addNewPhysicsItemToField(playerPaddle);
        var ball = makeBall();
        cartographer.balls.push(ball);
        addNewPhysicsItemToField(ball);
    }

    function buildSingleLineMap() {
        var offset = {
            x: 50,
            y: 20
        }
        for (var i = offset.x; i < myCanvas.width - offset.x; i += offset.x) {
            for (var j = 0; j < 3; j++) {
                var nextBrick = makeBrick(offset.x, offset.y);
                nextBrick.transform.x = i + (16 * (-1 * j%2));
                nextBrick.transform.y = Math.round(myCanvas.height * (0.85-(j*0.07)));
                cartographer.bricks.push(nextBrick);
                addNewPhysicsItemToField(nextBrick);

            }
        }
        defaultBallAndPlayer();
        defaultWalls();
    }

    function removeDeadItems() {
        if (!scanningForDead) {
            scanningForDead = true;
            somethingDied = false;
            //console.log('something died');
            for (var i = Animator.renderItems.length - 1; i >= 0; i--) {
                if (Animator.renderItems[i].isDead) {
                    //console.log('removed renderitem');
                    Animator.renderItems.splice(i, 1);
                }
            }
            for (var i = physics.collisionItems.length - 1; i >= 0; i--) {
                if (physics.collisionItems[i].isDead) {
                    //console.log('removed collisionItem');
                    physics.collisionItems.splice(i, 1);
                }
            }
            for (var i = physics.staticCollisionItems.length - 1; i >= 0; i--) {
                if (physics.staticCollisionItems[i].isDead) {
                    //console.log('removed staticCollisionItem');
                    physics.staticCollisionItems.splice(i, 1);
                }
            }
            scanningForDead = false;
        }
    }

    function resetMap() {
        scoreboard.levelsCompleted++;
        var offset = {
            x: 50,
            y: 20
        }
        for (var ball in cartographer.balls) {
            if (cartographer.balls[ball].transform.y > Math.round(myCanvas.height * (0.65))) {
                cartographer.balls[ball].transform.y = Math.round(myCanvas.height * (0.62));
            }
        }
        cartographer.bricks = [];
        for (var i = offset.x; i < myCanvas.width - offset.x; i += offset.x) {
            for (var j = 0; j < 3; j++) {
                if (Math.random() > 0.15) {
                    var nextBrick = makeBrick(offset.x, offset.y);
                    nextBrick.transform.x = i + (16 * (-1 * j % 2));
                    nextBrick.transform.y = Math.round(myCanvas.height * (0.85 - (j * 0.07)));
                    cartographer.bricks.push(nextBrick);
                    addNewPhysicsItemToField(nextBrick);
                }
            }
        }
    }

    function Start() {
        buildSingleLineMap();
        Animator.animationLoop();
    }


    Start();
</script>

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/HighScores/Create.cshtml
@model HW8_game_eagley_kasner.HighScore

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HighScore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WavesCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WavesCompleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WavesCompleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/HighScores/Delete.cshtml
@model HW8_game_eagley_kasner.HighScore

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HighScore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WavesCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WavesCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/HighScores/Details.cshtml
@model HW8_game_eagley_kasner.HighScore

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HighScore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WavesCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WavesCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/HighScores/Edit.cshtml
@model HW8_game_eagley_kasner.HighScore

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HighScore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WavesCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WavesCompleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WavesCompleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/HighScores/Index.cshtml
@model IEnumerable<HW8_game_eagley_kasner.HighScore>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Points)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WavesCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Points)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WavesCompleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/Home/Index.cshtml
@model IEnumerable<HW8_game_eagley_kasner.HighScore>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">

    @using (Html.BeginForm( "Index", "Game"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="form-group">
                @Html.Label("Your game-name", htmlAttributes: new { @class = "control-label col-md-2" }) 
                <div class="col-md-10">
                    
                    @Html.Editor("PlayerName", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessage("PlayerName", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Index" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
        @if(Model!=null && Model.Count() > 0)
        {

            <table class="table">
                <caption>Current highscores:</caption>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Points)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WavesCompleted)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlayerName)
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Points)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WavesCompleted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlayerName)
                        </td>
                    </tr>
                }

            </table>
        }

        </div>

HW8-game-eagley-kasner/HW8-game-eagley-kasner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Game!</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Game!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jefferson Eagley & Aren Kasner - ISIT420: adv. data access - Bellevue College</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>